spring:
  application:
    name: Graduating-Server
  datasource:
    url: jdbc:mysql://localhost:3306/graduating
    username: root
    password: gnpp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 1234
