spring:
  application:
    name: Graduating-Server
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/graduating}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:gnpp}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 1234
secret:
  neis:
    apikey: ${NEIS_APIKEY}