spring:
  application:
    name: Graduating-Server
  datasource:
    url: jdbc:mariadb://${DB_URL}/${DB_NAME:graduating}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 1234
secret:
  neis:
    apikey: ${NEIS_APIKEY}